pub const BUTTON_BORDER_COLOR_OPEN_CLOSE: &str = "BUTTON_BORDER_COLOR_OPEN_CLOSE";
pub const BUTTON_TEXT_SOURCE: &str = "BUTTON_TEXT_SOURCE";
pub const BUTTON_BORDER_COLOR_SOURCE: &str = "BUTTON_BORDER_COLOR_SOURCE";
pub const BUTTON_BACKGROUND_COLOR_SOURCE: &str = "BUTTON_BACKGROUND_COLOR_SOURCE";
